# Generated by Django 6.0.6 on 2026-06-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizly_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='url',
            new_name='video_url',
        ),
    ]
