# Generated by Django 6.0.6 on 2026-06-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizly_app', '0002_rename_url_quiz_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='video_url',
            new_name='url',
        ),
    ]
